server:
    port: 8077
spring:
    data:
        neo4j:
            database: neo4jtest
    neo4j:
        authentication:
            password: 123456
            username: neo4j
        uri: bolt://localhost:7687 #neo4j://对应4.0?
    datasource:
        username: root
        password: root
        url: jdbc:mysql://localhost:3306/power_grid?serverTimezone=GMT&useSSL=false
        driver-class-name: com.mysql.cj.jdbc.Driver
#        type: com.zaxxer.hikari.HikariDataSource
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: false
