package com.gridgraphprocessing.construct.enums;

public enum DeviceType {
    DMS_CB_DEVICE,
    DMS_BS_DEVICE,
    DMS_DISCONNECTOR_DEVICE,
    DMS_GROUND_DISCONNECTOR,
    DMS_LD_DEVICE,
    DMS_SECTION_DEVICE,
    DMS_TR_DEVICE,
    ACLINEEND,
    ACLINESEGMENT,
    BREAKER,
    BUSBARSECTION,
    COMPENSATOR_P,
    COMPENSATOR_S,
    DISCONNECTOR,
    ENERGYCONSUMER,
    GROUNDDISCONNECTOR,
    TRANSFORMERWINDING
}
